### ISSUE TITLE
Table - remark-gfm is rendering an empty `<td />` element instead of not rendering it

### ISSUE THREAD

**Issue by gilisho** [remarkjs/remark-gfm#11]
### Subject of the issue

I have some css for my tables, and one of my users had a space after some row in the table.
In Github it renders well. However, using `react-markdown` it looks weird (image below). Turns out that while Github ignores this space, in `remark-gfm` there's an added `td` element which makes the UI look weird in my case...
I think it's a bug since it doesn't align with how Github is rendering the table.

### Your environment

*   **Packages**: `react-markdown` (version 5)

### Steps to reproduce

Example in `codesandbox.io`:
https://codesandbox.io/s/react-markdown-forked-4hj01

### Expected behavior

Should render the ordered list exactly like in Github:

| hello... | hi... |
| :----   | :----     |
| first cell | second cell and last |  
| first cell | second cell and last |

Notice the number of `<td />` elements in the first row - it's two elements in Github, whereas in `react-markdown` with `remark-gfm` it's three.

### Actual behavior

There's an excessive `<td />` element which is empty.
This is the UI:
![image](https://user-images.githubusercontent.com/40733156/109803346-9c236200-7c29-11eb-8bdc-7122a48fa0a9.png)

These are the HTML elements (the marked element is the redundant element):
![image](https://user-images.githubusercontent.com/40733156/109803329-975eae00-7c29-11eb-9ad5-340a87d80f9c.png)

**Comment by wooorm** [comment]
Your codesandbox does not display the screenshot you shared here?

**Comment by wooorm** [comment]
I cannot reproduce:

```
| a |
| - |
| b |SP
`

in micromark. I *can* reproduce:

```
| a |SP 
| - |
```

there

**Comment by gilisho** [comment]
I'm not sure I understand. The sandbox does reproduce this.
Maybe I got confused in the beginning but now it should appear ok.

This is the code in sandbox link:
```
import React from "react";
import "./styles.scss";
import ReactMarkdown from "react-markdown";
import gfm from "remark-gfm";

const markdown = `
| hello... | hi... |
| :----   | :----     |
| first cell | second cell and last |  
| first cell | second cell and last |

`;

export default function App() {
  return <ReactMarkdown plugins={[gfm]} children={markdown} />;
}
```

**Comment by wooorm** [comment]
Should be fixed. Your example worked fine now!

**Comment by gilisho** [comment]
Funny question but I still see the same UI in sandbox. What should I be doing to get the updated version?

**Comment by wooorm** [comment]
`npm update`

**Comment by gilisho** [comment]
Sorry but I still don't understand. 😅 
How can I see it working properly live on codesandbox? All the packages are updated to the latest version there.

**Comment by ChristianMurphy** [comment]
@wooorm's instructions are for testing locally.

> How can I see it working properly live on codesandbox? All the packages are updated to the latest version there.

That is a question for CodeSandbox support hello@codesandbox.io
